FROM python:3

RUN apt-get update -y && \
  apt-get install -y python-pip python-dev

ENV MONGODB_URL=mongodb://root:example@localhost/local?retryWrites=true&w=majority&authSource=admin

WORKDIR /

RUN pip install -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["python", "./main.py"]